DELETE http://localhost:3003/api/blogs/64bb78164709670820761484
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikdhd3JHdXJhIiwiaWQiOiI2NGJiNzc4ODQ3MDk2NzA4MjA3NjE0NzEiLCJpYXQiOjE2OTAwMDc2MDN9.fXTJGFj91-gOwvgnaB4ZnS5GIUf5IvKTfcmIObFrRWI

###
DELETE http://localhost:3003/api/blogs/64bb78164709670820761484
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsZWNCbGFuY2UiLCJpZCI6IjY0YmI3NzdhNDcwOTY3MDgyMDc2MTQ2ZCIsImlhdCI6MTY5MDAwNzY1MH0.7rv-Q2UQxpf2pp4GLsgAXmIJb9aoF7g-4x5Sz6Hsipw