POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Sample Blog",
  "author": "Alec Blance",
  "url": "http://github.com",
  "likes": 1
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsZWNCbGFuY2UiLCJpZCI6IjY0YmI3NzdhNDcwOTY3MDgyMDc2MTQ2ZCIsImlhdCI6MTY5MDAwNzU1M30.tnsX5yHSRw8S2sKW19SXQf3WMtZkV42bRqBb_E8qVJI

{
  "title": "Sample Blog 2",
  "author": "Alec Blance",
  "url": "http://github.com",
  "likes": 1
}

###
POST http://localhost:3003/api/blogs/64d6ef5ce6576a049c756418/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsZWNCbGFuY2UiLCJpZCI6IjY0ZDQyZDdlMWEzZGM1M2IxZDNkOTY3YyIsImlhdCI6MTY5MTgwNzA4OH0.Xlt6dj7OjsosPIyw_iirSNAvsYTCK3Rhq9-Z5L2KRnI

{
  "comment": "WOW COMMENT 2"
}