POST http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "Alec",
    "username": "AlecBlance",
    "password": "idk"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "Alec",
    "password": "idk"
}