DELETE http://localhost:3003/api/blogs/64bb81d49dcbf3ded1872b32
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikdhd3JHdXJhIiwiaWQiOiI2NGJiNzc4ODQ3MDk2NzA4MjA3NjE0NzEiLCJpYXQiOjE2OTAwMTA3Nzd9.yyWCK71hA9ufckJV-kRgzZALTZn9iERYNY-ldudpTYE

###
DELETE http://localhost:3003/api/blogs/64bb81d49dcbf3ded1872b32
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsZWNCbGFuY2UiLCJpZCI6IjY0YmI3NzdhNDcwOTY3MDgyMDc2MTQ2ZCIsImlhdCI6MTY5MDAxMDc2NH0.6L7wdyrvR-sxZ8P9iFBZHPTpAKYDEk6mIK4YfKbcOyQ